development:
  adapter: postgresql
  encoding: unicode
  database: tutorialSite_development
  pool: 5
  username: postgres
  password: nsp66uuj

test:
  adapter: postgresql
  encoding: unicode
  database: tutorialSite_test
  pool: 5
  username: postgres
  password: nsp66uuj